__version__ = "0.1.0"
__author__ = "Ramon Moraes"
__author_email__ = "ramonmoraes8080@gmail.com"
__license__ = "MIT"
__app_name__ = "endpoints"
__description__ = "ReST API Endpoint Mapper"
__long_description__ = "ReST API Endpoint Mapper"
